VEIOSS-709 | Restrict traders quarantined code 4 on OSS from register…
hmrc/ioss-registration-frontend pull request #148
Opened 2024-10-29 14:29 UTC by warrenskiwork1979

…ing on IOSS

2024-10-30 15:24 UTC, warrenskiwork1979 commented
retest this please

2024-10-30 15:38 UTC, DevAndyroo requested changes

2024-10-30 15:38 UTC, DevAndyroo commented on app/controllers/actions/CheckRegistrationFilter.scala
> +          // TODO -> Replace with correct redirect when created.
resolve todo before merge

2024-10-31 15:17 UTC, DevAndyroo approved these changes

2024-10-31 15:26 UTC, merged