VEIOSS-272 | Create audit event for create registration.
hmrc/ioss-registration-frontend pull request #33
Opened 2023-10-25 16:19 UTC by warrenskiwork1979

2023-10-31 14:29 UTC, DevAndyroo approved these changes

2023-10-31 14:30 UTC, DevAndyroo requested changes
see comment from accidental approval

2023-11-01 09:45 UTC, warrenskiwork1979 commented on app/controllers/CheckYourAnswersController.scala
> +              auditService.audit(RegistrationAuditModel.build(RegistrationAuditType.CreateRegistration, request.userAnswers, SubmissionResult.Success))
Have added response to audit model as requested.

2023-11-02 09:39 UTC, DevAndyroo approved these changes

2023-11-02 09:40 UTC, merged