VEIOSS-225 Build Amend Reg - The second chapter
hmrc/ioss-registration-frontend pull request #60
Opened 2023-11-14 15:44 UTC by pbyrne84

2023-11-24 15:25 UTC, pbyrne84 commented on app/controllers/CheckYourAnswersController.scala
> +      val previouslyRegisteredSummaryRow = PreviouslyRegisteredSummary.row(request.userAnswers, waypoints, thisPage, lockEditing = false)
Don't want to lock editing on CheckYourAnswers, Only on ChangeYourAnswers when the the answer is true

2023-11-24 15:52 UTC, pbyrne84 commented on app/controllers/actions/DataRequiredAction.scala
> +                                                     isInAmendMode: Boolean
Though this authAndGetData which is used everywhere

2023-11-24 15:55 UTC, pbyrne84 commented on app/controllers/amend/AmendCompleteController.scala
> +                                         override val messagesApi: MessagesApi,
Just ran auto-format and added isInAmendMode = true

2023-11-24 15:56 UTC, pbyrne84 commented on app/controllers/amend/ChangeRegistrationController.scala
> +      existingPreviousRegistrations = PreviousRegistration.fromEtmpPreviousEuRegistrationDetails(request.previousEURegistrationDetails),
Factory method fromEtmpPreviousEuRegistrationDetails converts to our format from ETMPs format.

2023-11-24 15:59 UTC, pbyrne84 commented on app/controllers/previousRegistrations/AddPreviousRegistrationController.scala
> +              Future.successful(Ok(view(form, waypoints, previousRegistrationRows, canAddCountries, incomplete)))
Just renamed to previousRegistrationRows as we have 2 previousRegistrations formats already(ETMP/Ours) and I found it a bit confusing

2023-11-24 16:13 UTC, pbyrne84 commented on app/controllers/previousRegistrations/DeletePreviousRegistrationController.scala
> +  private def getPreviousRegistration(waypoints: Waypoints, index: Index)
Just moved **getPreviousRegistration** so it is underneath where it is called

2023-11-24 16:15 UTC, pbyrne84 commented on app/controllers/previousRegistrations/PreviousIossNumberController.scala
> +                  case Some(activeMatch) if !waypoints.inAmend && activeMatch.matchType.isActiveTrader =>
Want to allow these actions in Amend mode

2023-11-24 16:20 UTC, pbyrne84 commented on app/models/Country.scala
> +  def fromCountryCodeUnsafe(countryCode: String): Country = {
Unsafe just means can throw an exception versus Eithering and cuts down on getOrElse(throw with a message) clutter.

2023-11-29 16:30 UTC, DevAndyroo requested changes

2023-11-29 16:30 UTC, DevAndyroo commented on app/pages/CannotRemoveExistingPreviousRegistrationsPage.scala
> +    throw new NotImplementedError("nextPageNormalMode is not implemented")
Do we need this instead of keeping the default nextPageNormalMode implementation?

2023-11-30 11:05 UTC, DevAndyroo approved these changes

2023-12-05 09:36 UTC, DevAndyroo approved these changes

2023-12-05 11:44 UTC, DevAndyroo approved these changes

2023-12-05 11:50 UTC, merged